window.NICO_LEARNING_PLAN = (() => {
  const profile = { id:'nico-english-2026', learner:'Nico', name:'Nico 的英语能力升级系统', shortName:'Nico · 英语升级', subtitle:'IELTS 6.5+ × 海外公司工作英语', startingLevel:'IELTS 5.5', target:'IELTS 6.5+（挑战 7.0）', targetHours:650, duolingo:false };
  const phases = [
    {id:1,name:'基础重建',range:'第 1–8 周',level:'B1 自动化',hours:10.5,milestone:'第 8 周基础测评',target:'Anki 词块稳定；B1 听力主旨约 70%；长句能在 10 秒内抓主干。'},
    {id:2,name:'B1 到 B2',range:'第 9–16 周',level:'B2 起步',hours:11.5,milestone:'第 16 周阶段测',target:'B1/B2 材料可跟；口语连续 90 秒；能完成工作邮件。'},
    {id:3,name:'B2 与 IELTS 桥接',range:'第 17–24 周',level:'IELTS 6.0–6.5',hours:12,milestone:'第 24 周模考 2',target:'首次完整模考进入 6.0–6.5；口语 2 分钟；写作 250 字。'},
    {id:4,name:'冲刺与职场英语',range:'第 25–36 周',level:'IELTS 6.5',hours:12.5,milestone:'第 36 周模考 4',target:'模考稳定 6.5；完成 5 分钟项目汇报与职场问答。'},
    {id:5,name:'稳定与求职',range:'第 37–52 周',level:'IELTS 6.5+',hours:13,milestone:'第 52 周年度验收',target:'IELTS 6.5+；30 分钟会议模拟；英文面试与求职材料完成。'},
  ];
  const rows = [
    [1,'建立系统','Toggl 建项目；Anki 模板；整理模糊词 100–150 个；British Council B1 2 条','Anki；British Council B1','首周日志与 2 分钟基线录音','完成首周日志；保存基线录音'],
    [1,'词汇自动化','Anki 10–15 新卡/天；B1 听力 3 条；每天 5 句长句拆解','Anki；British Council B1；ELSA','2 分钟连续口述','Anki 回顾准确率≥80%'],
    [1,'听辨与跟读','加入连读/弱读；Modern Family 片段 3 次；每天 shadowing','Language Reactor；Modern Family；ELSA','30–60 秒片段复述','复述覆盖≥60%信息'],
    [1,'月度小测','B1 听力小测；阅读 20–30 分钟；写 100 字；录音 2 分钟','British Council；Write & Improve','错误分类清单','词汇/听辨/语法/记忆/输出均有记录'],
    [1,'定语从句','每天 10 句拆句；Anki；B1 听力 3 条','Anki；British Council B1','长句主干笔记','10 秒找主干≥70%'],
    [1,'状语与名词从句','每天 5 句改写成简单英文；听力 3 条','Sentence Lab；British Council','长句复述录音','复述准确率≥70%'],
    [1,'Shadowing','Modern Family 3 片段；ELSA 5 次；1 次 1 分钟口述','Language Reactor；ELSA','1 分钟口述录音','停顿≤8 次'],
    [1,'月度测评','B1 听力与阅读小测；100–150 字写作','British Council；Write & Improve','M2 测评记录','B1 听力/阅读正确率≥70%'],
    [2,'B2 入口','British Council B2 2 条；IELTS Listening Section 1；Anki 70 张','British Council B2；IELTS Official','B2 首听记录','主旨理解≥60%'],
    [2,'题干词汇','整理 IELTS 题干动词与同义替换 50 组；1 分钟口述 4 次','Anki；IELTS Official','题干词汇表','识别正确率≥80%'],
    [2,'阅读结构','IELTS passage 精读；标段落功能；写 150–180 字','IELTS Official；Write & Improve','段落功能笔记','主旨判断≥80%'],
    [2,'第一次阶段测','Listening/Reading 半套；口语 1 分钟；写作 200 字','IELTS Official；ChatGPT','阶段测评包','至少一项达到 6.0 轨迹'],
    [2,'会议语言','学习 meeting/interview 场景；The Office 片段','British Council；The Office','会议词块库','会议词块≥30'],
    [2,'工作邮件','写 request/update/disagree 三封邮件并二改','Write & Improve；ChatGPT','三封工作邮件','基础错误明显减少'],
    [2,'口语扩展','观点—理由—例子—结论；2 分钟口述 3 次','ELSA；ChatGPT','2 分钟口述','结构完整、不散'],
    [2,'阶段测','IELTS Listening/Reading 半套；Writing 1 篇','IELTS Official；Write & Improve','M4 测评报告','排出四项问题优先级'],
    [3,'Listening Section 1–2','真题精听与同义替换','IELTS Official；Anki','Section 1–2 错题表','正确率≥80%'],
    [3,'Listening Section 3–4','讲座/讨论精听；口头总结','IELTS Official；British Council','讲座摘要','正确率≥65–70%'],
    [3,'Reading 计时','1 passage/20 分钟；错题回原文','IELTS Official','阅读定位记录','定位信息时间缩短'],
    [3,'完整模考 1','四科完整一次；详细复盘','IELTS Official；Write & Improve','首次总分与单项分','完成错因分类'],
    [3,'弱项专项 1','按模考最弱项加码 2 小时','个人错题库；IELTS Official','专项前后对比','单项提升≥0.5 目标'],
    [3,'Writing Task 2','结构模板；2 篇练习；二次修改','Write & Improve；IELTS Official','250–280 字二稿','25–35 分钟完成'],
    [3,'Speaking Part 2/3','Part 2 2 分钟与 Part 3 追问','ELSA；ChatGPT','口语模拟录音','训练表现 6.0–6.5'],
    [3,'完整模考 2','完整模考与复盘','IELTS Official','模考 2 报告','总分至少 6.0，挑战 6.5'],
    [4,'Design English','介绍项目、设计决策和 trade-off；5 分钟 presentation','ChatGPT；技术文档','5 分钟项目录音','完整 5 分钟表达'],
    [4,'Meeting English','agree/disagree/clarify/interrupt/summarize','British Council；ChatGPT','15 分钟 mock meeting','完成会议纪要'],
    [4,'IELTS L/R 计时','听力与阅读各 2 套 section','IELTS Official','计时正确率表','稳定 6.5 轨迹'],
    [4,'写作与工作邮件','Task 2 与 work email 并行','Write & Improve；ChatGPT','文章与邮件二稿','逻辑清晰、少低级错误'],
    [4,'无字幕理解','YouTube/剧集片段盲听','Language Reactor；YouTube','盲听摘要','首听主旨≥75%'],
    [4,'Shadowing 强化','每日 10–15 分钟，录音对比','ELSA；Language Reactor','录音对比','语速与重音更稳定'],
    [4,'追问训练','ChatGPT 连续追问 5 轮','ChatGPT','追问会话记录','即时回答≥70%'],
    [4,'完整模考 3','完整 IELTS 模考','IELTS Official','模考 3 报告','目标 6.5±0.5'],
    [4,'英文周报','写 100–150 字 status/blocker/next step','ChatGPT；British Council','英文项目周报','信息自然、清楚'],
    [4,'Design critique','5 分钟讲设计并接受追问','ChatGPT','设计讲解录音','回答≥5 个追问'],
    [4,'英文面试','自我介绍与 project deep dive','ChatGPT；STAR 框架','10 分钟 mock interview','完成连续问答'],
    [4,'完整模考 4','完整 IELTS 模考','IELTS Official','模考 4 报告','目标≥6.5'],
    [5,'Band descriptor','逐条对照 Speaking/Writing 标准','IELTS Official','最大短板清单','明确 3 个短板'],
    [5,'Writing sprint','每周 2 篇 Task 2','Write & Improve','错误 Top 10','形成个人错误库'],
    [5,'Speaking sprint','Part 2/3 严格计时','ELSA；ChatGPT','口语冲刺录音','2 分钟不停顿；讨论 3–4 分钟'],
    [5,'完整模考 5','完整考试环境','IELTS Official','模考 5 报告','6.5；任一单项不低于 6.0'],
    [5,'Full mock 1','完整模考 1，检查时间管理','IELTS Official','时间管理记录','无超时'],
    [5,'Work meeting','30 分钟 agenda→discussion→decision→recap','ChatGPT；British Council','会议录音与纪要','英文完成率≥80%'],
    [5,'Presentation','5–8 分钟项目汇报与 Q&A','ChatGPT','汇报录音','结构清晰、能接追问'],
    [5,'完整模考 6','完整 IELTS 模考','IELTS Official','模考 6 报告','目标 6.5–7.0'],
    [5,'弱项修复','只练最弱两项','个人错题库','弱项趋势图','单项分数稳定'],
    [5,'Mock interview','behavioral/project/conflict 三次面试','ChatGPT；STAR 框架','三次面试复盘','每次复盘 3 个问题'],
    [5,'Final full mock','完整模考，严格计时','IELTS Official','最终模考成绩','两次连续达到目标区间'],
    [5,'Real-world week','一周用英文完成输入/输出任务','Language Reactor；ChatGPT','最终能力报告','完成真实任务证据'],
    [5,'考试窗口','正式考试或最后一次官方样题模拟','IELTS Official','高频错误清单','按固定节奏完成'],
    [5,'英文求职材料','英文简历、LinkedIn Summary、portfolio case study','ChatGPT；LinkedIn','完整英文求职材料','完成 1 份求职包'],
    [5,'英文面试与 critique','英文面试 2 次；mock design critique 1 次','ChatGPT','30 分钟工作英语记录','持续对话 30 分钟'],
    [5,'年度复盘与 C1 路线','更新词汇库、录音、模考成绩和输出证据','学习记录','年度成果包','制定后续 6 个月计划'],
  ];
  const byPhase = Object.fromEntries(phases.map(phase => [phase.id, phase]));
  const weeks = rows.map(([phase,title,focus,materials,output,check], index) => ({ week:index+1, phase, title, focus, materials, output, check, hours:byPhase[phase].hours, tasks:[] }));
  const materials = [
    {name:'Anki',use:'词块与句型间隔重复',phase:'全年，每天 20–30 分钟',points:['每张卡绑定搭配、例句与音频','M1–2 每天 10–15 张新卡','回顾准确率目标 85–90%'],url:'https://apps.ankiweb.net/'},
    {name:'British Council LearnEnglish',use:'B1/B2 听力、语法与职场输入',phase:'全年，每周 3–4 次',points:['优先按 B1/B2 分级选择','盲听→看稿→复听→复述','会议、电话、采访都可作为训练素材'],url:'https://learnenglish.britishcouncil.org/free-resources/listening'},
    {name:'Language Reactor',use:'影视与 YouTube 逐句精听',phase:'全年，每周 3–5 次',points:['30–90 秒片段反复训练','英文字幕、查词、保存句子','不要整集裸看'],url:'https://www.languagereactor.com/help/basic'},
    {name:'ELSA Speak',use:'发音与流利度反馈',phase:'全年，每天 10 分钟',points:['发音练习后立即重说','保存前后录音','把问题带进真实表达'],url:'https://elsaspeak.com/'},
    {name:'ChatGPT',use:'口语追问、会议和面试模拟',phase:'全年，每天 5–15 分钟',points:['一次只问一个问题','先完成表达，再集中纠错','保留录音或会话文字'],url:'https://chatgpt.com/'},
    {name:'IELTS 官方样题',use:'模块测评与完整模考',phase:'第 9 周起逐步增加',points:['从 M3 开始模块测试','每次严格计时','所有错误分类后再练'],url:'https://ielts.org/take-a-test/preparation-resources/sample-test-questions'},
    {name:'Write & Improve',use:'写作反馈与二次修改',phase:'第 9 周起',points:['先独立写作','根据反馈重写第二版','记录重复错误类型'],url:'https://writeandimprove.com/'},
    {name:'Toggl Track',use:'有效学习时长记录',phase:'全年',points:['Project：English 2026–27','只记录有任务和产物的时间','每周日查看报告'],url:'https://toggl.com/track/'},
  ];
  return { profile, phases, weeks, materials, materialCategories:['全部','词汇','听力','口语','写作','考试','职场'], materialTypes:['词汇','听力','听力','口语','口语','考试','写作','职场'] };
})();
